### ISSUE TITLE
DM fans can not connect to the server

### ISSUE THREAD

**Issue by danielwaw** [rapejim/dmiot2mqtt#1]
Hi Raul, thank you for your wonderful project. I've installed the docker image and run the container on my device. While the fans could not connect to the host. I post the logs below and pls take a look.

stderr: [dmoit2mqtt] WARNING  No MQTT config found, falling back to localhost
stderr: [dmoit2mqtt] INFO     Serving on 0.0.0.0:31270
stderr: [dmoit2mqtt] INFO     Client ('172.17.0.1', 41398) connected.
stderr: MQTT connection failed: OSError("Multiple exceptions: [Errno 111] Connect call failed ('::1', 1883, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1883)")
stderr: Connection failed: ConnectException(OSError("Multiple exceptions: [Errno 111] Connect call failed ('::1', 1883, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1883)"))
stderr: MQTT connection failed: OSError("Multiple exceptions: [Errno 111] Connect call failed ('::1', 1883, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1883)")
stderr: Reconnection attempt failed: ConnectException(OSError("Multiple exceptions: [Errno 111] Connect call failed ('::1', 1883, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1883)"))
stderr: MQTT connection failed: OSError("Multiple exceptions: [Errno 111] Connect call failed ('::1', 1883, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1883)")
stderr: Reconnection attempt failed: ConnectException(OSError("Multiple exceptions: [Errno 111] Connect call failed ('::1', 1883, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1883)"))
stderr: MQTT connection failed: OSError("Multiple exceptions: [Errno 111] Connect call failed ('::1', 1883, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1883)")
stderr: Reconnection attempt failed: ConnectException(OSError("Multiple exceptions: [Errno 111] Connect call failed ('::1', 1883, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1883)"))
stderr: Maximum number of connection attempts reached. Reconnection aborted
stderr: Unhandled exception in client_connected_cb
stderr: transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
stderr: Traceback (most recent call last):
stderr:   File "/usr/local/lib/python3.12/site-packages/amqtt/client.py", line 439, in _connect_coro
stderr:     conn_reader, conn_writer = await asyncio.open_connection(
stderr:                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.12/asyncio/streams.py", line 48, in open_connection
stderr:     transport, _ = await loop.create_connection(
stderr:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1130, in create_connection
stderr:     raise OSError('Multiple exceptions: {}'.format(
stderr: OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 1883, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1883)
stderr: 
stderr: During handling of the above exception, another exception occurred:
stderr: 
stderr: Traceback (most recent call last):
stderr:   File "/usr/local/lib/python3.12/site-packages/amqtt/client.py", line 233, in reconnect
stderr:     return await self._do_connect()
stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.12/site-packages/amqtt/client.py", line 250, in _do_connect
stderr:     return_code = await self._connect_coro()
stderr:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.12/site-packages/amqtt/client.py", line 489, in _connect_coro
stderr:     raise ConnectException(e)
stderr: amqtt.client.ConnectException: Multiple exceptions: [Errno 111] Connect call failed ('::1', 1883, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1883)
stderr: 
stderr: The above exception was the direct cause of the following exception:
stderr: 
stderr: Traceback (most recent call last):
stderr:   File "/app/dmiot2mqtt.py", line 260, in client_connected_callback
stderr:     await dreammakeriotclient.async_run()
stderr:   File "/app/dmiot2mqtt.py", line 152, in async_run
stderr:     await self.mqtt_client.connect(MqttConfig.get_uri())
stderr:   File "/usr/local/lib/python3.12/site-packages/amqtt/client.py", line 170, in connect
stderr:     return await self.reconnect()
stderr:            ^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.12/site-packages/amqtt/client.py", line 242, in reconnect
stderr:     raise ConnectException("Too many connection attempts failed") from e
stderr: amqtt.client.ConnectException: Too many connection attempts failed

**Comment by RmG152** [comment]
Hello,

Have you modified the configuration file “dmiot2mqtt.ini” to point to your mqtt server?

If you used the project docker-compose.yml, you will have it in “/docker/dmiot2mqtt/config”.

**Comment by danielwaw** [comment]
> Hello,
> 
> Have you modified the configuration file “dmiot2mqtt.ini” to point to your mqtt server?
> 
> If you used the project docker-compose.yml, you will have it in “/docker/dmiot2mqtt/config”.

Yes, I've done it and it's not working. Pls see the logs below:

stderr: MQTT connection failed: ConnectionRefusedError(111, "Connect call failed ('192.168.1.115', 1883)")
stderr: Connection failed: ConnectException(ConnectionRefusedError(111, "Connect call failed ('192.168.1.115', 1883)"))
stderr: MQTT connection failed: ConnectionRefusedError(111, "Connect call failed ('192.168.1.115', 1883)")
stderr: Reconnection attempt failed: ConnectException(ConnectionRefusedError(111, "Connect call failed ('192.168.1.115', 1883)"))
stderr: MQTT connection failed: ConnectionRefusedError(111, "Connect call failed ('192.168.1.115', 1883)")
stderr: Reconnection attempt failed: ConnectException(ConnectionRefusedError(111, "Connect call failed ('192.168.1.115', 1883)"))
stderr: MQTT connection failed: ConnectionRefusedError(111, "Connect call failed ('192.168.1.115', 1883)")
stderr: Reconnection attempt failed: ConnectException(ConnectionRefusedError(111, "Connect call failed ('192.168.1.115', 1883)"))
stderr: Maximum number of connection attempts reached. Reconnection aborted

**Comment by danielwaw** [comment]
Finally, I got it work, while I gave up using docker method and run it in linux instead. Thank you all the same.
